---
# tasks file for r1soft-agent
- name: Create a repo
  when:
  - ansible_facts['distribution'] == "Ubuntu"
  - ansible_facts['distribution_version'] == "16.04"
  shell: |
    echo deb http://repo.r1soft.com/apt stable main >> /etc/apt/sources.list
    wget http://repo.r1soft.com/r1soft.asc
    apt-key add r1soft.asc 

- name: Update repo
  when:
  - ansible_facts['distribution'] == "Ubuntu"
  - ansible_facts['distribution_version'] == "16.04"
  shell: |
    apt-get update -y

- name: install r1soft agent
  when:
  - ansible_facts['distribution'] == "Ubuntu"
  - ansible_facts['distribution_version'] == "16.04"
  package: 
    name: serverbackup-enterprise-agent   
    state: present
  notify:
  - Start r1soft agent
  # - Install key

      
- name: Install key
  when:
  - ansible_facts['distribution'] == "Ubuntu"
  - ansible_facts['distribution_version'] == "16.04"
  shell: "r1soft-setup   --get-key   http://{{ r1soft_server_ip }}"