---
- name: Install Wordpress
  hosts: all
  become: true
  become_method: sudo
  tasks:
  - name: Install prerequisites
    when:
    - ansible_facts['distribution'] == "Amazon"
    - ansible_facts['distribution_version'] == "2"
    package:
      name: "{{ item }}"
      state: present
    with_items:
    - httpd
    - php
    - php-mysql
    - telnet
