---
- name: Zipping playbook
  hosts: all
  become: true
  become_method: sudo
  tasks: 
  - name: Zip Files over 90 days
    raw: 'find /var/log/ -type f -name "*.log" -mtime +90 -exec gzip -v9 {} +'
  - name: Zip Files over 100M
    raw: 'find /var/log/ -type f -name "*.log" -size +100M -exec gzip -v9 {} +' 
...
