---
# handlers file for r1soft-agent
- name: Start r1soft agent
  when:
    - ansible_facts['distribution'] == "Ubuntu"
    - ansible_facts['distribution_version'] == "16.04"
  systemd:
    name: sbm-agent
    state: restarted
    enabled: true
    
- name: Install key
  when:
  - ansible_facts['distribution'] == "Ubuntu"
  - ansible_facts['distribution_version'] == "16.04"
  shell: "r1soft-setup   --get-key   http://{{ r1soft_server_ip }}"